services:
  web:
    image: php:8.1-apache
    container_name: simple_mvc
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public
    command: >
      bash -c "
      apt-get update && apt-get install -y git unzip &&
      sed -ri -e 's!/var/www/html!/var/www/html/public!g' /etc/apache2/sites-available/*.conf &&
      sed -ri -e 's!/var/www/!/var/www/html/public!g' /etc/apache2/apache2.conf /etc/apache2/conf-available/*.conf &&
      a2enmod rewrite &&
      curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer &&
      cd /var/www/html && composer install --no-dev --optimize-autoloader &&
      apache2-foreground
      "